name: 1. Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Morphe Beta'
        type: choice
        options:
          - 'Morphe'
          - 'Morphe Beta'
          - 'RVE-anddea-stable'
          - 'RVE-anddea-beta'
          - 'Twitter Piko Stable'
          - 'Twitter Piko Beta'
          - 'Revanced'
          - 'Revanced Beta'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rv:
    name: Patch Revanced Stable
    if: ${{ github.event.inputs.org == 'Revanced' || inputs.org == 'Revanced' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        run: bash src/build/Revanced.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_rv_beta:
    name: Patch Revanced Beta
    if: ${{ github.event.inputs.org == 'Revanced Beta' || inputs.org == 'Revanced Beta' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rvb
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rvb
        if: steps.check-gh-rvb.outputs.internet_error == '0'
        run: bash src/build/Revanced-Beta.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rvb
        if: steps.check-gh-rvb.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_morphe:
    name: Patch Morphe
    if: ${{ github.event.inputs.org == 'Morphe' || inputs.org == 'Morphe' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-morphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        run: bash src/build/morphe.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-morphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_morphe_beta:
    name: Patch Morphe Beta
    if: ${{ github.event.inputs.org == 'Morphe Beta' || inputs.org == 'Morphe Beta' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe-beta
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-morphe-beta
        if: steps.check-gh-morphe-beta.outputs.internet_error == '0'
        run: bash src/build/morphe-beta.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-morphe-beta
        if: steps.check-gh-morphe-beta.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_rve_anddea_stable:
    name: Patch RVX Anddea Stable
    if: ${{ github.event.inputs.org == 'RVE-anddea-stable' || inputs.org == 'RVE-anddea-stable' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve-anddea-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-anddea
        if: steps.check-gh-rve-anddea-stable.outputs.internet_error == '0'
        run: bash src/build/Anddea-Revanced-Extended.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_anddea_stable
          path: |
            ./release/*.apk
  release_rve_anddea_stable:
    name: Release RVX Anddea Stable
    needs: patch_rve_anddea_stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_anddea_stable
          path: ./release
      - name: Releasing APK files
        uses: ./.github/actions/release
  patch_rve_anddea_beta:
    name: Patch RVX Anddea Beta version
    if: ${{ github.event.inputs.org == 'RVE-anddea-beta' || inputs.org == 'RVE-anddea-beta' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        run: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve-anddea-beta
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-anddea-beta
        if: steps.check-gh-rve-anddea-beta.outputs.internet_error == '0'
        run: bash src/build/Anddea-Revanced-Extended-Beta.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rve-anddea-beta
        if: steps.check-gh-rve-anddea-beta.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_twitter_piko_stable:
    name: Patch Twitter Piko Stable
    if: ${{ github.event.inputs.org == 'Twitter Piko Stable' || inputs.org == 'Twitter Piko Stable' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-piko-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        run: bash src/build/Piko.sh
      - name: Releasing APK files
        id: release-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_twitter_piko_beta:
    name: Patch Twitter Piko Beta
    if: ${{ github.event.inputs.org == 'Twitter Piko Beta' || inputs.org == 'Twitter Piko Beta' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-piko-beta
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-piko-beta
        if: steps.check-gh-piko-beta.outputs.internet_error == '0'
        run: bash src/build/Piko-Beta.sh
      - name: Releasing APK files
        id: release-piko-beta
        if: steps.check-gh-piko-beta.outputs.internet_error == '0'
        uses: ./.github/actions/release
